config/routes.rb
Rails.application.routes.draw do
  get 'test_controller/index'

  get 'courses/index'

  get 'greeter/hello'

  get 'greeter/goodbye'

  root 'courses#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coursera.rb
class Coursera
  include HTTParty

  base_uri 'https://api.coursera.org/api/courses.v1'
  default_params fields: "photoUrl,description", q: "search"
  format :json

  def self.for term
    get("", verify: false, query: {query: term})["elements"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'jhu'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ["Alex", "Joe", "Michael"]
    @name = random_names.sample
    @time = Time.now
    @times_displayed ||= 0
    @times_displayed += 1
  end
  def goodbye
  end
end

app/controllers/test_controller_controller.rb
class TestControllerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")
  end
end

app/helpers/test_controller_helper.rb
module TestControllerHelper
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<table border="1">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @courses.each do |course| %>
  <tr class=<%= cycle('even', 'odd') %>>
    <td><%= image_tag(course["photoUrl"], size: "150x150")%></td>
    <td><%= course["name"] %></td>
    <td><%= course["description"] %></td>
  </tr>
  <% end %>
</table>

app/views/greeter/goodbye.html.erb
<% random_names = ["Alex", "Joe", "Michael"] %>
<h1>Bye, <%= random_names.sample %>!</h1>
<p>The time now is <%= Time.now %></p>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %>!</h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> time(s).</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/test_controller/index.html.erb
<h1>TestController#index</h1>
<p>Find me in app/views/test_controller/index.html.erb</p>